update QUnit, use Karma, make some of CI work locally as well (#672)
* workflows: Rename "CI" to "Release"

Rename this to make space for a separate "CI" workflow that will
run continuous integration and testing jobs for commits and PRs.

* workflows: add CI workflow for unit tests and support running locally

* Load qunit package from npm, this is the start of a larger transition.
  ref at https://github.com/kiwix/kiwix-js/issues/554.

* Update QUnit from 2.3 to 2.13.

* Use Karma for the running of unit tests (instead of Nightwatch).

  While it was possible to use a fake "UI" test to open the QUnit
  web page with Nightwatch, this had numerous limitations:

  - relies on fragile and unsupported DOM scraping to collect
    test results, which breaks between framework versions.
    ref https://github.com/kiwix/kiwix-js/pull/660.

  - severely limits debugging information for failing tests.

  - cannot easily be reproduced or debugged locally from the command-line
    as the Nightwatch config was pinned to Sauce Labs, and creating
    a local configuration is not easy because Nightwatch has a hard
    requirement for installing and running a WebDriver server.
    People usually do not have this installed and it's non-trivial
    to set up and keep working in the long term, and across multiple
    different software projects.

  - cannot easily be run in a secure container separate from your
    personal computer, thus putting personal data at risk.

  - lacks wider integration and plugins to enrich unit testing,
    such as test coverage reports.

  Using Karma means:
  - We can run 'npm test' locally during development and have it
    automatically run the tests in headless Firefox and Chrome
    and report back, all from the command-line.
  - The same exact same stack is also used in CI with SauceLabs
    for additional browser coverage (same as before).
  - It has no external dependencies other than the plain web
    browser itself. This means if you have a development container
    (e.g. based on Docker) that has Node.js + Firefox + Chromium,
    you can run the tests there without exposing anything from
    your personal computer, besides the current directory.
    <https://timotijhof.net/posts/2019/protect-yourself-from-npm/>
  - In a future change, we can plug in karma-coverage to generate
    a test coverage report, to submit to Codecov or Coveralls.
    ref https://github.com/kiwix/kiwix-js/issues/528.

* I have pinned the version of 'http-server' and 'nightwatch'
  in package.json so that these don't silently upgrade in a way
  that may introduce security issues or drop compatibility for
  the environment we currently support.

Fixes https://github.com/kiwix/kiwix-js/issues/653.

* Re-enable unit and UI tests in latest Edge

The tests were disabled after https://github.com/kiwix/kiwix-js/pull/499
due to an issue with the Edge version that was the default "edge" on
SauceLabs in May 2019 (not sure which version that was, the last pre-Chromium
Edge version was 44, which was passing, so perhaps SauceLabs defaulted
to a beta release, or used a much older version like 15-18?)

Now that Edge uses Chromium, try re-enabling the tests.

Fixes https://github.com/kiwix/kiwix-js/issues/502.

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -1,65 +1,101 @@
-# This sets the environment for building Kiwix JS store packages and runs the build script
-
 name: CI
 
-# Controls when the action will run.
 on:
-  release:
-  # Triggers the workflow on publishing a release
-    types:
-      - published
-  schedule:
-  # Nightly run at 01:37 UTC (avoiding the usual midnight surge and rounded times)
-    - cron: '37 1 * * *'
-  # Allows us to run this workflow manually from the Actions tab
-  workflow_dispatch:
+  - push
+  - pull_request
+  # Allow running manually
+  - workflow_dispatch
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
-    runs-on: ubuntu-20.04
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
+  # This job runs always, including for remote pull requests, and
+  # has external dependencies or special permission needs, besides a
+  # local install of Node.js, Firefox, and Chromium or Chrome.
+  #
+  # You can run these same tests locally in your own developer
+  # environment via `npm ci && npm test`.
+  tests-basic:
+    # Packages 'firefox' and 'google-chrome' are pre-installed.
+    #
+    # https://github.com/actions/virtual-environments/blob/ubuntu20/20201210.0/images/linux/Ubuntu2004-README.md
+    runs-on: ubuntu-20.04
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      # Clone the repo and checkout the commit for which the workflow was triggered
       - uses: actions/checkout@v2
 
-      # Set up secret files from encrypted secrets
-      - name: Set up secret files
-        env:
-          SSH_KEY: ${{ secrets.SSH_KEY }}
-          CHROME_EXTENSION_KEY: ${{ secrets.CHROME_EXTENSION_KEY }}
-        shell: bash
-        run: |
-          echo "$SSH_KEY" > ./scripts/ssh_key
-          chmod 600 ./scripts/ssh_key
-          echo "$CHROME_EXTENSION_KEY" > ./scripts/kiwix-html5.pem
-          chmod 600 ./scripts/kiwix-html5.pem
+      # Install Node.js LTS
+      - uses: actions/setup-node@v2
+        with:
+          node-version: 10.x
 
-      # Set up the environment
-      - name: Setup environment
-        shell: bash
-        run: |
-          sudo apt-get update
-          sudo apt-get --yes install ./scripts/ubuntu_touch_packages/*.deb
+      - name: Install dependencies
+        run: npm ci
 
-      # Runs the build scripts
-      - name: Run the build scripts
+      - name: Unit tests (Linux)
+        run: npm test
+
+  # This job only runs when SauceLabs credentials are available
+  # (e.g. direct pushes and local non-fork PRs) and is used to
+  # run tests on additional operating systems and browsers.
+  tests-secure:
+    # Ideally this would be `if: secrets.SAUCE_USERNAME` or `if: fork`, which Travis CI
+    # supported, but GitHub Actions does not. When a commit or PR is from a source (non-fork)
+    # repo, the secrets are loaded only after the conditions are checked, not before.
+    # https://github.community/t/if-expression-with-context-variable/16558
+    #
+    # WARNING: GitHub evaluates workflow secrets and their protections always from the
+    # perspective of the source repo. This means you cannot test secure jobs from a
+    # forked repostiory. Unlike Travis, any secrets you configure in the fork are ignored.
+    # To test a secure job, you will have to create a fresh repo under a different name,
+    # add your secrets, and push to this additional remote from your local clone.
+    #
+    # One workaround is to check the secret from an early bash step and return early, but
+    # that would display this job as having succeeded instead of skipped, which is confusing.
+    #
+    # Another way is to approximate the secret permission as best we can and hope
+    # we don't accidentally run it when we shouldn't. Note that this condition only
+    # decides whether the job runs, not the secrets loads, so it doesn't need to be
+    # match perfectly. At worst it might in some edge case skip or run when it shouldn't
+    # and simply fail due to absence of secrets.
+    # https://github.community/t/have-github-action-only-run-on-master-repo-and-not-on-forks/140840
+    # https://github.community/t/distinguish-between-forked-pr-and-own-pr/16678/2
+    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
+    runs-on: ubuntu-20.04
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions/setup-node@v2
+        with:
+          node-version: 10.x
+      - name: Install dependencies
+        run: npm ci
+
+      - name: QUnit tests (Cross-browser)
         env:
-          MOZILLA_API_SECRET: ${{ secrets.MOZILLA_API_SECRET }}
-          MOZILLA_API_KEY: ${{ secrets.MOZILLA_API_KEY }}
-          TAG_NAME: ${{ github.event.release.tag_name }}
-        shell: bash
-        # Switch -t indicates a tag release (public release); add -d for dry run (for testing)
-        # BEFORE the -v switch (because $TAG_NAME is empty for non-public builds)
+          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
+          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
+        run: npm run test-unit-saucelabs
+
+
+      # Start a SauceLabs tunnel for Nightwatch (Karma does this automatically)
+      - name: Start tunnel for End-to-end tests
+        uses: saucelabs/sauce-connect-action@v1.1.2
+        with:
+          username: ${{ secrets.SAUCE_USERNAME }}
+          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
+
+      - name: End-to-end tests (Cross-browser)
+        env:
+          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
+          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
         run: |
-          # Run xvfb to make Chrome/Chromium believe it has a display. Else it fails signing the package
-          Xvfb -ac :99 -screen 0 1280x1024x16 &
-          export DISPLAY=:99
-          if [ "x$TAG_NAME" = "x" ]; then
-            ./scripts/create_all_packages.sh
-          else
-            ./scripts/create_all_packages.sh -t -v "$TAG_NAME"
-          fi
+          ./node_modules/.bin/http-server . &
+          sleep 2
+          curl "http://localhost:8080" | head
+          # The free account on Sauce does not allow more than 5 concurrent sessions (including the main one)
+          # So we separate the recent and old browsers in order to respect this limit.
+          # REMINDER: Keep this list in sync with the Unit tests, in tests/karma.conf.saucelabs.js
+          ./node_modules/.bin/nightwatch -c nightwatch.js --env firefox,chrome,edge
+          ./node_modules/.bin/nightwatch -c nightwatch.js --env edge40,edge44
+          ./node_modules/.bin/nightwatch -c nightwatch.js --env firefox45,chrome58,ie11
+          pkill node || echo "Node process not running (anymore)"
